### ISSUE TITLE
come up with `maddr` scheme for BTC Silent Payment Addresses

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/dap#12]
Credit to @aparkersquare for this idea

[BIP 0352](https://en.bitcoin.it/wiki/BIP_0352), aka "Silent Payments," proposes a protocol that allows an individual to share a static address that the sender uses to generate the actual payable address. This is done by combining the recipient's static address with a secret scalar derived from their own private key and the recipient's public key resulting in a unique stealth address for each transaction without revealing the link on the blockchain. The recipient can use their private key to detect and spend the funds from this address

This works really well with money addresses.

**Comment by aparkersquare** [comment]
For reference here, examples of the existing bitcoin maddr schemes (taken from the spec) are

*BTC LNURL*
`urn:btc:lnurl:https://someurl.com`

*BTC Address*
`urn:btc:addr:1LMcKyPmwebfygoeZP8E9jAMS2BcgH3Yip`


I think that naturally leads us to

*BTC Silent Payment Address*
`urn:btc:spaddr:sp1qqweplq6ylpfrzuq6hfznzmv28djsraupudz0s0dclyt8erh70pgwxqkz2ydatksrdzf770umsntsmcjp4kcz7jqu03jeszh0gdmpjzmrf5u4zh0c`

Personally I feel like "Silent Payments" is a slightly confusing name. I tend to think of it as "reusable address", so one option might be `raddr` for the scheme, but that may just be me.

`spaddr` is more obviously related to the name of the BIP, so overall a better choice.

Interestingly the Abstract for [BIP-0352](https://github.com/bitcoin/bips/blob/master/bip-0352.mediawiki) says "This document specifies a protocol for static payment addresses in Bitcoin ...", so you can equally associate `spaddr` with "static payment address" and it still works fine.
